### ISSUE TITLE
[環境・新規]デプロイフローの自動化

### ISSUE THREAD

**Issue by h-yoshikawa44** [h-yoshikawa44/jigsaw-like-puzzle#21]
## 対象環境
本番

## 目的
Firebaseへのデプロイは手動で行っても容易ではあるが、自動化することでさらに効率化する。

## 作業内容
- GitHub Actions + React + Firebase の自動デプロイのやり方を調査
- GitHub Actions の設定ファイルを作成
- masterにpush時に自動デプロイが実行されるようにする

**Comment by h-yoshikawa44** [comment]
## デプロイ用アクション
- [GitHub Action for Firebase](https://github.com/marketplace/actions/github-action-for-firebase)

こちらを使用。

firebase CLI でトークンを取得して、secrets に FIREBASE_TOKEN として設定しておく。
```
$ firebase login:ci
```

```yml
- name: Deploy to Firebase Hosting
   uses: w9jds/firebase-action@v2
   with:
     args: deploy --only hosting --message \"${{ github.event.head_commit.message }}\"
   env:
     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```
